#!/usr/bin/env python3
"""Generate index pages for the teach-me lesson sites.

Auto-discovers every top-level folder that contains a `lessons/` directory,
builds a per-subject index linking each lesson (and any reference pages), and
builds a combined landing page at the repo root. New subjects need no config.
"""
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.IGNORECASE | re.DOTALL)
H1_RE = re.compile(r"^#\s+(.*)$", re.MULTILINE)


def page_title(htmlfile: Path) -> str:
    """Pull the <title> from an HTML file, falling back to the filename."""
    try:
        text = htmlfile.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return htmlfile.stem
    m = TITLE_RE.search(text)
    if m:
        return re.sub(r"\s+", " ", m.group(1)).strip()
    return htmlfile.stem


def subject_meta(subject: Path) -> tuple[str, str]:
    """Return (title, description) for a subject from its MISSION.md."""
    title = subject.name.replace("-", " ").title()
    desc = ""
    mission = subject / "MISSION.md"
    if mission.exists():
        text = mission.read_text(encoding="utf-8", errors="ignore")
        m = H1_RE.search(text)
        if m:
            heading = m.group(1).strip()
            # "Mission: Climb ~300 rating points" -> use the part after the colon
            desc = heading.split(":", 1)[-1].strip() if ":" in heading else heading
    return title, desc


CSS = """
:root{--ink:#2b2722;--muted:#564e44;--rule:#d8cfc2;--bg:#fbf8f3;--accent:#7a4a2b;--chip:#efe7da;--card:#fff}
*{box-sizing:border-box}
html{font-size:20px}
body{background:var(--bg);color:var(--ink);font-family:"Iowan Old Style","Palatino Linotype",Palatino,Georgia,serif;font-size:1.06rem;line-height:1.6;margin:0;padding:3rem .9rem 5rem}
.wrap{max-width:48rem;margin:0 auto}
.kicker{font-size:.78rem;letter-spacing:.18em;text-transform:uppercase;color:var(--muted);margin:0 0 .3rem}
h1{font-size:2.2rem;line-height:1.12;margin:0 0 .4rem;font-weight:600}
.lede{font-size:1.1rem;color:#433d35;margin:0 0 2rem}
a.card{display:block;text-decoration:none;color:inherit;background:var(--card);border:1px solid var(--rule);border-radius:12px;padding:1rem 1.2rem;margin:.7rem 0}
a.card:hover{border-color:var(--accent)}
a.card .t{font-size:1.12rem;font-weight:600;color:var(--accent)}
a.card .s{font-size:.92rem;color:var(--muted);margin-top:.15rem}
h2{font-size:.95rem;letter-spacing:.05em;text-transform:uppercase;color:var(--accent);border-bottom:1px solid var(--rule);padding-bottom:.35rem;margin:2.6rem 0 1rem}
.back{display:inline-block;font-size:.9rem;color:var(--muted);text-decoration:none;margin-bottom:1.4rem}
.back:hover{color:var(--accent)}
.empty{color:var(--muted);font-style:italic}
footer{margin-top:3rem;font-size:.82rem;color:var(--muted);border-top:1px solid var(--rule);padding-top:1rem}
"""


def doc(title: str, body: str) -> str:
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<style>{CSS}</style>
</head>
<body><div class="wrap">
{body}
<footer>Generated by build_site.py</footer>
</div></body>
</html>
"""


def build_subject(subject: Path) -> dict:
    title, desc = subject_meta(subject)
    lessons_dir = subject / "lessons"
    lessons = sorted(lessons_dir.glob("*.html")) if lessons_dir.exists() else []

    body = ['<a class="back" href="../index.html">&larr; All subjects</a>']
    body.append('<p class="kicker">Lessons</p>')
    body.append(f"<h1>{html.escape(title)}</h1>")
    if desc:
        body.append(f'<p class="lede">{html.escape(desc)}</p>')

    body.append("<h2>Lessons</h2>")
    if lessons:
        for f in lessons:
            rel = f"lessons/{f.name}"
            body.append(
                f'<a class="card" href="{rel}"><div class="t">{html.escape(page_title(f))}</div></a>'
            )
    else:
        body.append('<p class="empty">No lessons yet.</p>')

    ref_dir = subject / "reference"
    refs = sorted(ref_dir.glob("*.html")) if ref_dir.exists() else []
    if refs:
        body.append("<h2>Reference</h2>")
        for f in refs:
            body.append(
                f'<a class="card" href="reference/{f.name}"><div class="t">{html.escape(page_title(f))}</div></a>'
            )

    (subject / "index.html").write_text(doc(title, "\n".join(body)), encoding="utf-8")
    return {"slug": subject.name, "title": title, "desc": desc, "count": len(lessons)}


def main() -> None:
    subjects = sorted(
        p for p in ROOT.iterdir() if p.is_dir() and (p / "lessons").is_dir()
    )
    cards = [build_subject(s) for s in subjects]

    body = ['<p class="kicker">Teach Me</p>', "<h1>My Lessons</h1>"]
    body.append('<p class="lede">Self-directed learning, one quick lesson at a time.</p>')
    for c in cards:
        n = c["count"]
        sub = f'{n} lesson{"s" if n != 1 else ""}'
        if c["desc"]:
            sub += f' &middot; {html.escape(c["desc"])}'
        body.append(
            f'<a class="card" href="{c["slug"]}/index.html">'
            f'<div class="t">{html.escape(c["title"])}</div>'
            f'<div class="s">{sub}</div></a>'
        )
    (ROOT / "index.html").write_text(doc("My Lessons", "\n".join(body)), encoding="utf-8")
    print(f"Built {len(cards)} subject(s): " + ", ".join(c["slug"] for c in cards))


if __name__ == "__main__":
    main()
